import { ParsedMpcFile, Observation, CandidateReport } from "@/types/mpc";

/**
 * Parses a standard Minor Planet Center (MPC) 80-column fixed-width observation report
 * generated by Astrometrica or astronomical observatories.
 */
export function parseMpcReport(fileContent: string): ParsedMpcFile {
  const lines = fileContent.split(/\r?\n/);

  let observatoryCode = "";
  let contact = "";
  let observers: string[] = [];
  let measurers: string[] = [];
  let telescope = "";
  let starCatalog = "";

  const rawObservations: Observation[] = [];

  for (const rawLine of lines) {
    const line = rawLine;

    // 1. Header lines
    if (line.startsWith("COD ")) {
      observatoryCode = line.substring(4).trim();
      continue;
    }
    if (line.startsWith("CON ")) {
      contact = line.substring(4).trim();
      continue;
    }
    if (line.startsWith("OBS ")) {
      observers = line
        .substring(4)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      continue;
    }
    if (line.startsWith("MEA ")) {
      measurers = line
        .substring(4)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      continue;
    }
    if (line.startsWith("TEL ")) {
      telescope = line.substring(4).trim();
      continue;
    }
    if (line.startsWith("NET ")) {
      starCatalog = line.substring(4).trim();
      continue;
    }

    // 2. 80-column observation lines (must be at least ~70 chars and not comment)
    if (line.length >= 70 && !line.startsWith("#")) {
      const candidateCode = line.substring(5, 12).trim();
      if (!candidateCode) continue;

      const isDiscovery = line[12] === "*";
      const datePart = line.substring(15, 32).trim(); // "YYYY MM DD.ddddd"
      const raPart = line.substring(32, 44).trim(); // "HH MM SS.ss"
      const decPart = line.substring(44, 56).trim(); // "+DD MM SS.s"
      const magStr = line.substring(65, 70).trim();
      const band = line[70] || "R";
      const obsCode = line.length >= 80 ? line.substring(77, 80).trim() : observatoryCode;

      // Convert RA "HH MM SS.ss" to decimal hours
      const [raH, raM, raS] = raPart.split(/\s+/).map(Number);
      const raHours = (raH || 0) + (raM || 0) / 60 + (raS || 0) / 3600;

      // Convert Dec "+DD MM SS.s" to decimal degrees
      const decSign = decPart.startsWith("-") ? -1 : 1;
      const cleanDec = decPart.replace(/[+-]/, "");
      const [decD, decM, decS] = cleanDec.split(/\s+/).map(Number);
      const decDegrees = decSign * ((decD || 0) + (decM || 0) / 60 + (decS || 0) / 3600);

      // Parse UTC date from "YYYY MM DD.ddddd"
      const dateTokens = datePart.split(/\s+/);
      let utcDate = new Date();
      if (dateTokens.length >= 3) {
        const year = parseInt(dateTokens[0], 10);
        const month = parseInt(dateTokens[1], 10) - 1;
        const dayDecimal = parseFloat(dateTokens[2]);
        const day = Math.floor(dayDecimal);
        const dayFraction = dayDecimal - day;
        const totalSeconds = dayFraction * 86400;
        const hours = Math.floor(totalSeconds / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const seconds = Math.floor(totalSeconds % 60);
        utcDate = new Date(Date.UTC(year, month, day, hours, minutes, seconds));
      }

      rawObservations.push({
        candidateCode,
        isDiscovery,
        dateStr: datePart,
        utcDate,
        raRaw: raPart,
        decRaw: decPart,
        raHours,
        decDegrees,
        magnitude: parseFloat(magStr) || 0,
        band,
        observatoryCode: obsCode || observatoryCode,
        rawLine: line,
      });
    }
  }

  // 3. Group by candidate code
  const candidatesMap = new Map<string, Observation[]>();
  for (const obs of rawObservations) {
    const existing = candidatesMap.get(obs.candidateCode) || [];
    existing.push(obs);
    candidatesMap.set(obs.candidateCode, existing);
  }

  const candidates: CandidateReport[] = [];
  for (const [code, obsList] of candidatesMap.entries()) {
    const hasAsterisk = obsList.some((o) => o.isDiscovery);
    const avgMag = obsList.reduce((acc, curr) => acc + curr.magnitude, 0) / (obsList.length || 1);

    obsList.sort((a, b) => a.utcDate.getTime() - b.utcDate.getTime());

    // Calculate motion rate (speed in arcsec/hr) if >= 2 observations
    let speedArcsecPerHour: number | undefined;
    if (obsList.length >= 2) {
      const first = obsList[0];
      const last = obsList[obsList.length - 1];
      const dtHours = (last.utcDate.getTime() - first.utcDate.getTime()) / (1000 * 3600);

      if (dtHours > 0) {
        // Delta RA in arcsec: (delta RA in hours) * 15 * cos(dec) * 3600
        const avgDecRad = ((first.decDegrees + last.decDegrees) / 2) * (Math.PI / 180);
        const dRaArcsec = (last.raHours - first.raHours) * 15 * 3600 * Math.cos(avgDecRad);
        const dDecArcsec = (last.decDegrees - first.decDegrees) * 3600;
        const totalDistArcsec = Math.sqrt(dRaArcsec * dRaArcsec + dDecArcsec * dDecArcsec);

        speedArcsecPerHour = parseFloat((totalDistArcsec / dtHours).toFixed(2));
      }
    }

    candidates.push({
      candidateCode: code,
      isNewDiscovery: hasAsterisk,
      observationCount: obsList.length,
      observations: obsList,
      avgMagnitude: parseFloat(avgMag.toFixed(1)),
      firstSeen: obsList[0]?.utcDate,
      lastSeen: obsList[obsList.length - 1]?.utcDate,
      speedArcsecPerHour,
    });
  }

  return {
    observatoryCode,
    contact,
    observers,
    measurers,
    telescope,
    starCatalog,
    candidates,
    totalObservations: rawObservations.length,
  };
}

/**
 * Extracts Pan-STARRS / Catalina Sky Survey image set IDs from raw text or table pasted from IASC.
 * e.g., matches "PS1-26A-01", "PS1_26A_02", "G96-24K02"
 */
export function extractImageSetIds(pastedText: string): string[] {
  const regex = /\b(PS[12]|G96|703)[-_ ]?([0-9]{2}[A-Z])[-_ ]?([0-9]{2,3})\b/gi;
  const matches = [...pastedText.matchAll(regex)];

  return Array.from(
    new Set(matches.map((m) => `${m[1].toUpperCase()}-${m[2].toUpperCase()}-${m[3]}`))
  );
}
